version: 2.1
jobs:
  build_storybook_and_notify:
    docker:
      - image: circleci/node:lts
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
      - run: yarn workspace @caddijp/components build-storybook

      - store_artifacts:
          path: packages/components/storybook-static
      - run: yarn moxci packages/components/storybook-static/index.html

workflows:
  version: 2
  workflow:
    jobs:
      - build_storybook_and_notify
