name: publish Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx lerna exec --no-bail -- 'can-npm-publish && npm publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
