name: compressed-size

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: compressed-size-action
        uses: preactjs/compressed-size-action@2.4.0
        with:
          repo-token: '${{ secrets.github_token }}'
          pattern: './packages/components/esm/**/*.js'
          exclude: '{**/*.map,**/node_modules/**}'
